#!/usr/bin/env python3
"""Update the version in the manifest file."""

import json
import sys
from pathlib import Path

MANIFEST = "custom_components/ukr_hmc/manifest.json"


def main(version: str) -> None:
    """Update the manifest version."""
    manifest_path = Path(MANIFEST)

    with manifest_path.open() as file:
        data = json.load(file)

    data["version"] = version.removeprefix("v")

    with manifest_path.open("w") as file:
        json.dump(data, file, indent=2)
        file.write("\n")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        main(sys.argv[1])
    else:
        print("Please provide a version argument.")  # noqa: T201
