name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v7

      - name: 🐍 Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: 🏷️ Bump manifest version
        run: python scripts/bump_version ${{ github.ref_name }}

      - name: 📦 Create zip package
        working-directory: custom_components/ukr_hmc
        run: zip -r ukr-hmc.zip .

      - name: 📤 Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_components/ukr_hmc/ukr-hmc.zip
          asset_name: ukr-hmc.zip
          tag: ${{ github.ref }}
          overwrite: true
